# Generated by Django 5.1.2 on 2024-11-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA_Asistent', '0005_alter_finance_budget_alter_finance_current_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysuggestion',
            old_name='content',
            new_name='assistant_seggestion',
        ),
        migrations.RemoveField(
            model_name='dailysuggestion',
            name='relevance',
        ),
        migrations.AddField(
            model_name='dailysuggestion',
            name='user_message',
            field=models.TextField(default=''),
        ),
    ]
